name: Create Release PR

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: git fetch --tags --unshallow

      - name: Generate Changelog
        id: changelog
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^)
          echo "Dernier tag dÃ©tectÃ© : $LAST_TAG"
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          git log $LAST_TAG..HEAD --pretty=format:"%s" \
          | awk '
            /^feat/ { f = f "\n- ðŸš€ " $0 }
            /^fix/ { x = x "\n- ðŸ› " $0 }
            /^core/ { c = c "\n- âš™ï¸ " $0 }
            !/^(feat|fix|core)/ { u = u "\n- ðŸ”¸ " $0 }
            END {
              print "## ðŸš€ Features" f "\n\n## ðŸ› Fixes" x "\n\n## âš™ï¸ Core" c "\n\n## ðŸ”¸ Non classÃ©" u
            }
          ' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create PR develop â†’ main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: release ${{ github.ref_name }}"
          title: "ðŸ”– Release ${{ github.ref_name }}"
          body: "${{ steps.changelog.outputs.CHANGELOG }}"
          base: main
          branch: develop
